Gemfile.lock, app/models/user.rb, db/migrate/20220228031633_devise_create_users.rb, db/schema.rb
Model, migration, validation for User
=> User model

Gemfile.lock, app/models/music.rb, app/models/user.rb, db/migrate/20220228031633_devise_create_users.rb, db/migrate/20220228101037_create_musics.rb, db/schema.rb, test/models/music_test.rb
I created the music migration and model with validation
=> Music model

app/models/music.rb
fixed a mistake in the naming of the validation method
=> fixed a mistake in the naming of the validation method

app/assets/stylesheets/application.scss, app/assets/stylesheets/components/_button.scss, app/assets/stylesheets/components/_card.scss, app/assets/stylesheets/components/_index.scss, app/assets/stylesheets/components/_text.scss, app/views/pages/_teacher_exercise_card.html.erb, app/views/pages/home.html.erb
Added teacher exercise card with two buttons. 
with hover effect for the button
=> Add teacher exercise card

app/models/music.rb, db/migrate/20220301050809_add_references_to_music.rb, db/migrate/20220301052010_remove_reference_from_exercise.rb, db/migrate/20220301063158_add_status_to_music.rb, db/schema.rb
Following the change in schema after my discussion with Doug (see picture below)
- Added foreign keys `exercise` and `user` to music.
- Removed foreign key `music` on exercise
- Updated belongs_to for music and exercise models
=> Add refs to music

app/assets/stylesheets/components/_navbar.scss, app/javascript/packs/application.js, app/views/layouts/application.html.erb, app/views/shared/_navbar.html.erb
Fixed navbar dropdown and changed the color back to main color purple.
=> Fixed navbar dropdown and changed color

app/assets/stylesheets/components/_footer.scss
I changed the color to "$purple"
and I delete a style from le wagon UI kitt
=> modified footer color

Gemfile, Gemfile.lock, app/models/user.rb, app/views/shared/_navbar.html.erb, config/environments/development.rb, config/environments/production.rb, config/storage.yml, db/migrate/20220301102411_create_active_storage_tables.active_storage.rb, db/schema.rb, db/seeds.rb
Setup cloudinary
Added avatar picture to the seeds and in the navbar
=> Setup cloudinary

app/assets/stylesheets/components/_footer.scss
I fixed the footer position
We don't need 'position: absolute' on the footer
=> fixed footer position

app/assets/stylesheets/components/_button.scss, app/assets/stylesheets/components/_footer.scss, app/models/exercise.rb, app/views/exercises/index.html.erb, app/views/pages/home.html.erb, db/seeds.rb
=> Fix add exercise button z index

app/models/exercise.rb, app/views/exercises/index.html.erb, db/seeds.rb
difficutly rating is currently a number, will put the logic for easy hard and medium tomorrow
=> Exercise seeds cards on index

app/assets/stylesheets/components/_footer.scss, app/views/pages/home.html.erb, app/views/shared/_footer.html.erb, db/seeds.rb
I fixed the hover color so that it is easier to see.
also fixed the alignment from this :
to this:
=> Hover sns change edited footer

app/models/music.rb, db/seeds.rb
- seed for one example of music
- seed for status of music
=> music seed

app/controllers/reviews_controller.rb, db/migrate/20220301053232_create_reviews.rb, db/schema.rb
Following Markie's comments on the reviews Controller I:
- used strong params
- change the default of the vote from 1 to 0
I couldn't manage to change the value with a new migration, so I modified an old one.
Please run db:drop db:create db:migrate db:seed
=> Refactor review

app/controllers/musics_controller.rb, app/views/musics/new.html.erb, config/routes.rb, test/controllers/musics_controller_test.rb
Branched from main to create the `add-music-controller-with-policies-branch`
@km111444 You can branch from `add-music-controller-with-policies-branch` when creating pundit. That way we can still get easy code to review and make sure it works altogether before merging into `main`
@abauville Not 100% on what to expect coming from the music form yet so I will need to make changes depending on your response. 
If I remember correctly, the status was going to change depending on their action. For example, `in_progress` or `finished`.
`Check` button will not alter the status but `saves` the current form, but `Submit` button will `save` the current form and update status?
=> controller and routes

app/controllers/application_controller.rb, app/controllers/exercises_controller.rb, app/controllers/musics_controller.rb, app/views/exercises/_player_exercise_card.html.erb, app/views/musics/new.html.erb, config/routes.rb
Merging here while Kanae works on pundit, otherwise likely to cause pundit issues when trying to use.
=> Update music controller

db/seeds.rb
Now all exercises have music. (I hope)
before
after
=> seed modify

app/models/user.rb
The User was missing has_many :reviews, dependent: :destroy. That was preventing seeding on heroku (because it refused to delete the users)
=> user was missing has_many :reviews, dependent: :destroy

db/seeds.rb
The pictures were commented in the seed for some reason. That was causing the crash on heroku
=> uncommented the picture seeds

app/controllers/exercises_controller.rb, app/controllers/reviews_controller.rb, app/views/exercises/_results_card.html.erb, yarn.lock
results card now has a working form that submits the comment to that particular exercise from a particular user. 
after submitting the feedback, it leads to the index exercise page with an alert that specifies that the feedback has been submitted. alert might need to be reformatted for the future. but not a priority.
=> Add form to results card

app/views/exercises/index.html.erb
the logic is implemented however, the seeds aren't varied in such a way that it shows some "in progress" **(as yellow)** cards as well, as stated in my other [issue](https://github.com/abauville/neighbor-studio/issues/69).
I added that task in the Trello backlog because its not a priority right now, but the code is working fine
=> Colors are working fine 

app/views/exercises/_player_exercise_card.html.erb, app/views/exercises/index.html.erb, app/views/shared/_review_card.html.erb
=> avatar working, cleaned  up index page

app/assets/stylesheets/components/_banner.scss, app/assets/stylesheets/components/_button.scss, app/assets/stylesheets/components/_index.scss, app/views/pages/home.html.erb
=> Home page done. super simple at the moment

app/javascript/components/changeScrollButtonStyle.js
As suggested by Markie (https://github.com/abauville/lickwars/issues/73) I added a condition to check if there was a button. There might be something more elegant. But it does the job
=> added a conditional to fix issue 73

app/javascript/controllers/score_controller.js
Keyboard input for note height and selection. I'm copying the input convention of museScore. So far:
- up/down arrows: shift the note up/down by a semitone
- cmd + up/down: shift the note up/down by an octave
- left/right: select previous/next note
- A, B, C, D, E, F, G keys: input the note with that name
I started with note lengths, but it will work best if we merge the notes and note_values string directly in the database. So, I'm gonna work on that next
=> Score keyboard input

app/views/exercises/index.html.erb
=> Removed the chord progression symbols on the exercise card 

app/assets/stylesheets/components/_footer.scss, app/views/shared/_footer.html.erb
1. resize the footer
**before**
**after**
2. remove the ':' from name
**before**
'Kanae:'
**after**
'Kanae'
3. open each links in another tab
Please let me know if you all have some suggestions!
=> Footer modify

app/assets/stylesheets/components/_button.scss, app/views/exercises/_tone.html.erb
this is the final image
originally i had play attempt, but it was too long and made the buttons uneven : like this
=> attempt button fix

app/views/shared/_navbar.html.erb
When I sign up(create new account), this error occured
but when I gave a default picture, it works like this.
=> Fix sign up error

app/assets/stylesheets/components/_button.scss, app/controllers/exercises_controller.rb, app/controllers/musics_controller.rb, app/javascript/controllers/score_controller.js, app/views/exercises/_tone.html.erb, app/views/exercises/index.html.erb
Removed the submit button  so that its only check like this:
if the notes are correect it changes to a contune button which leads to the modal that asks for a review
else, it says incorrect and you have to continue the exercise, until correct
=> Rake function

app/assets/stylesheets/components/_score.scss, app/javascript/models/music.js, app/javascript/models/score.js
Displays music of arbitrary length!!
=> More bars on score

app/javascript/controllers/score_controller.js, app/javascript/models/boom_box.js
You click, you hear it. You press a key, you hear it!
Builds on top of pull requests #84 and #88. Those should be merged first.
=> Selected note plays sound

app/assets/stylesheets/components/_navbar.scss
- bigger logo
- centered 'Login' button
=> Logo and login button's position

app/assets/stylesheets/components/_avatar.scss, app/views/exercises/index.html.erb
=> Navbar size ( more slim )

app/assets/stylesheets/components/_card.scss
https://user-images.githubusercontent.com/96113893/157179330-6e1c986e-9e3d-4077-85ae-2c099791bcd2.mov
- changed card's size thinner
- changed card's shadow
=> Change card's size( thinner ) , shadow

app/assets/stylesheets/components/_banner.scss, app/assets/stylesheets/components/_card.scss, app/controllers/exercises_controller.rb, app/controllers/musics_controller.rb, app/views/exercises/_exercises_container.html.erb, app/views/layouts/application.html.erb
=> Card orderd by difficulty

app/assets/stylesheets/application.scss, app/assets/stylesheets/components/_card.scss, app/assets/stylesheets/components/_index.scss, app/assets/stylesheets/components/_player_card.scss, app/javascript/components/index.js, app/javascript/controllers/score_controller.js, app/javascript/controllers/tone_controller.js, app/views/exercises/_player_exercise_card.html.erb, app/views/exercises/_score.html.erb, app/views/exercises/_tone.html.erb, app/views/exercises/show.html.erb
I rearranged the show page following Doug's advice. We can discuss details (colors etc...). The main point here is that:
- The player card is clearly delineated: it is the light purple card
- Inside the card is what belongs to the player: i.e. the score and the purple play button. On hover the purple button says "play input"
- The button for the check and the question are outside of the card in a corner. They're also in a different color
Maybe we should make the question button even more obvious so that the player knows what to do (i.e. click that button when he arrives on the page). To make it more obvious we could make it e.g. red(ish), center, BIG, animated, etc...
I also deleted the radio buttons that were causing troubles with Heroku
=> Rearranged the show page following Doug's advice

app/views/exercises/_exercise_index_card.html.erb, app/views/exercises/_exercises_container.html.erb
=> sign-out working

app/controllers/exercises_controller.rb, app/controllers/musics_controller.rb, app/javascript/controllers/score_controller.js, app/javascript/controllers/tone_controller.js, app/models/music.rb, app/views/exercises/_form.html.erb, app/views/exercises/_tone.html.erb
The show page check works again. The exercise creation also works. I also fixed a bug where it was not checking the first time if you never played that exercise (because the check was only in the update route)
=> Fixed form show page

app/assets/stylesheets/components/_button.scss, app/javascript/components/changeScrollButtonStyle.js
fixes #116 
Fixed `add new exercise` button on teacher/exercises page.
=> Fix 'add new ex' button

app/assets/stylesheets/components/_button.scss, app/assets/stylesheets/config/_fonts.scss, app/views/exercises/_score.html.erb
=> Note buttons

app/controllers/exercises_controller.rb, app/models/music.rb, app/queries/musics_query.rb
=> filtered by exercises not owned by user

app/models/exercise.rb, app/views/exercises/_level_card.html.erb
=> used after_create callback to set description

app/views/layouts/application.html.erb
=> Change title(Lickwars→Melodict)

app/assets/stylesheets/components/_banner.scss, app/views/pages/home.html.erb
=> fixed with no conflicts, home page is more responsive

app/assets/stylesheets/components/_index.scss, app/assets/stylesheets/components/_title.scss, app/assets/stylesheets/config/_fonts.scss, app/views/exercises/index.html.erb, app/views/exercises/show.html.erb, app/views/teacher/exercises/index.html.erb
=> changed font style

app/views/exercises/_form.html.erb, app/views/exercises/new.html.erb
added a help button for user expereience
=> Help modal teacher card

app/views/exercises/_level_card.html.erb
Solved the issue with the exercise not showing up.
Below logged in as Tom.
=> Fixed exercise not showing up

app/assets/stylesheets/components/_button.scss
added shadow to all green buttons
s
=> added shadow to buttons

app/assets/stylesheets/components/_alert.scss
=> alerts are now even on pages

app/assets/stylesheets/components/_card.scss, app/assets/stylesheets/pages/exercise/_index.scss, app/views/exercises/_exercises_container.html.erb, app/views/exercises/_level_card.html.erb, app/views/exercises/_progress_bar.html.erb, app/views/exercises/index.html.erb
Changed font size, search bar size and card color and hover effect.
=> updated player index page

app/assets/stylesheets/components/_button.scss, app/assets/stylesheets/components/_player_card.scss, app/javascript/components/changeScrollButtonStyle.js, app/javascript/controllers/score_controller.js, app/javascript/models/music.js, app/javascript/models/score.js, app/views/exercises/_score.html.erb
Fixed various things around the score:
- backspace creates a rest
- keep inputting notes of the selected value
- when inputting a note on a rest, determine the octave based on the previous note (if the previous note is also a rest, go back up to five notes to find a reference)
- fixed some bugs with note value inputs. It is still not perfect. The logic is not very flexible, it should probably be rewritten from the ground up
- show the currently selected note value by highlighting a button
- added a keyboard shortcut to buttons
- changed the style of note value and play button
=> Improve score input

app/assets/stylesheets/components/_alert.scss, app/views/exercises/_form.html.erb, app/views/layouts/application.html.erb
=> New teacher exercise  page

app/views/teacher/exercises/_teacher_exercise_card.html.erb
`teacher/exercises` cards now link to the teachers exercise so they can listen/attempt
=> made card clickable

app/assets/stylesheets/components/_card.scss, app/assets/stylesheets/pages/exercise/_index.scss, app/views/exercises/_exercise_index_card.html.erb, app/views/exercises/_exercises_container.html.erb, app/views/exercises/_level_card.html.erb, app/views/exercises/index.html.erb
=> set progress container level with search

app/javascript/controllers/score_controller.js, app/views/exercises/_score.html.erb
There were two buttons with the same html id: that was causing the bug.
I also forgot the number 2 keyboard shortcut
=> Fix broken note value button

app/assets/stylesheets/components/_banner.scss, app/assets/stylesheets/components/_navbar.scss, app/views/pages/home.html.erb
=> updated spacing and added linear gradient to background img

app/views/exercises/_help_card.html.erb
picture still wasn't showing up on Heroku. so I changed the IMG tag to the helper. as per Doug suggestion
=> used helper instead to show picture on heroku. 

app/assets/stylesheets/components/_score.scss, app/javascript/controllers/score_controller.js, app/javascript/controllers/tone_controller.js, app/javascript/models/boom_box.js, app/javascript/models/music.js, app/views/exercises/_score.html.erb, app/views/exercises/_tone.html.erb, db/seed_helper.rb
Added a few nice things for playback. First I had to refactor the playing to use Tone.Part to time and schedule events. That allowed me to:
- add play/stop function on the attempt and question buttons
- the stop button reverts to "play" automatically when the melody is over
- note highlight during attempt playback. 
I'm gonna tweak the visual of the highlight tomorrow. I'll also add a highlight of the measure when the question is played. And for the check button too if I have time
=> Playback feedback

app/views/exercises/_help_card.html.erb
=> Delete ';' from help card

app/javascript/controllers/score_controller.js
Fixed the bug with the buttons.
I forgot that the values coming from HTML are string. Now, I explicitly cast the noteValue coming from the button to a Number
=> cast the selectedNoteValue to Number

db/seed_helper.rb, db/seeds.rb
fixed the rest values in the twinkle seed and made prettier seeds for the index page
=> Better seeds

app/assets/stylesheets/components/_button.scss, app/assets/stylesheets/components/_card.scss, app/assets/stylesheets/components/_player_card.scss, app/assets/stylesheets/config/_colors.scss, app/views/exercises/_exercise_index_card.html.erb, app/views/teacher/exercises/_teacher_exercise_card.html.erb
I tried to make the indexes page and the show page coherent through the color schemes, also by reusing the navbar color as the main purple
Index page:
I also adjusted the font size on the card (which was the header size)
Teacher's page: 
- I also removed the chord progression because we don't input it in the exercise
Show page:
=> Index style

app/assets/stylesheets/components/_card.scss, app/assets/stylesheets/config/_colors.scss, app/views/exercises/_exercise_index_card.html.erb
https://user-images.githubusercontent.com/96113893/157821632-df6502ab-54c4-4054-955b-88440a555ff4.mov
I changed the color and hover effect to avoid confusing teacher-index-card / player-index-card.
=> teacher's exercise index card   color change
